#!/usr/bin/env bash

sudo pip install awscli

aws \
  --region="$AWS_REGION" \
opsworks create-deployment \
  --stack-id="$OPSWORKS_STACK_ID" \
  --app-id="$OPSWORKS_APP_ID" \
  --instance-ids="[$OPSWORKS_INSTANCE_IDS]" \
--command='{"Name": "deploy"}'
